# ---------------------------------------------------------------------
# Ultrasonic Sensor Test
# Hardware: Seeed XIAO ESP32-C6 8MB
# Sensors: JSN-RS04t
# Autor: Roland Ortner
# Date: 2024-09-07
# ---------------------------------------------------------------------

# Substitution of global strings
substitutions:
  # Device properties
  devicename: "distance-sensor"
  friendly_name: "Ultrasonic Distance Sensor"
  short_name: "Distance Sensor" # used for fallback hotspot
  comment: "Ultrasonic sensor with Seeed XIAO ESP32-C6"
  area: Garden
  icon: mdi:water-well

  project_name:       "ortner.distance_sensor"
  project_version:    "2025.07.27.001"
  pin_ultrasonic_tx:   GPIO18 # GPIO20 Tx/Echo
  pin_ultrasonic_rx:   GPIO20 # GPIO18 Rx/Trig
  
packages:
  esp32c6: !include common/esp32c6.yaml
  base: !include common/base.yaml

# UART mode (do not set stop_bits, rx_buffer_size for jsn_sr04t) (https://esphome.io/components/uart.html)
uart:
  - id: uart_ultrasonic
    tx_pin: $pin_ultrasonic_tx # Tx/Echo GPIO20
    rx_pin: $pin_ultrasonic_rx # Rx/Trig GPIO18
    baud_rate: 9600
    debug:
      direction: BOTH
      dummy_receiver: false
      sequence:
        - lambda: UARTDebug::log_hex(direction, bytes, ' ');

logger:

sensor:
  # Ultrasonic sensor AJ-SR04M distance (https://markus-haack.com/watertank-esphome/)
  # mounted in 50 mm pipe with feld to remove reflections
  
  - platform: "jsn_sr04t" # [ultrasonic|jsn_sr04t] 
    id: distance
    name: "Distance"
    model: "jsn_sr04t" # aj_sr04m|jsn_sr04t Try original model instead of aj_sr04m
    uart_id: uart_ultrasonic
    unit_of_measurement: "cm"
    update_interval: 3s
    filters: 
      - filter_out: nan
      - multiply: 100 # convert mm in cm

  #- platform: "ultrasonic" # [ultrasonic|jsn_sr04t] 
  #  id: distance
  #  name: "Distance"
  #  #model: "jsn_sr04t" # [jsn_sr04t|aj_sr04m] AJ-SR04M does only work with mode jsn_sr04t!
  #  #uart_id: uart_ultrasonic
  #  unit_of_measurement: "cm"
  #  accuracy_decimals: 2
  #  pulse_time: 20us
  #  trigger_pin: $pin_ultrasonic_tx # Tx/Echo GPIO20
  #  echo_pin: $pin_ultrasonic_rx # Rx/Trig GPIO18
  #  timeout: 30m
  #  force_update: True
  #  update_interval: 10s
  #  #filters:
  #  #  - filter_out: nan

#  - platform: "jsn_sr04t"  # aj_sr04t
#    name: "Livello Tanica"
#    id: livello_tanica
#    update_interval: 1s
#    unit_of_measurement: "m"
#    accuracy_decimals: 2
#    filters:
#      - filter_out: nan  # Filtra le letture non valide
#      - sliding_window_moving_average:
#          window_size: 10
#          send_every: 10
