# -----------------------------------------------------------------
# Base Configuration for ESPHome
# requires secret.yaml
# ---------------------------------------------------------------------

esphome:
  name: "${devicename}"
  friendly_name: "${friendly_name}"
  comment: "${comment}"
  area: "${area}"
  project:
    name: "${project_name}"
    version: "${project_version}"

# Enable WiFi configuration (https://esphome.io/components/wifi)
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #fast_connect: true
  power_save_mode: LIGHT
  manual_ip:
    static_ip: 192.168.178.99
    gateway: 192.168.178.1
    subnet: 255.255.255.0
    dns1: 192.168.178.1
    dns2: 8.8.8.8
  #enable_btm: true
  #enable_rrm: true
  
  # Enable fallback hotspot with captive portal
  ap:
    ssid: "${short_name} Hotspot"
    password: !secret wifi_ap_password

captive_portal:

# Enable logging (https://esphome.io/components/logger)
logger:
  level: VERBOSE
  hardware_uart: USB_SERIAL_JTAG # Enable logging via USB-C (https://esphome.io/components/logger.html?highlight=usb%2Bcdc#hardware-uarts)
  # baud_rate: 0 # Turn off serial logging (TBD)

# Enable Over The Air (OTA) updates (https://esphome.io/components/ota)
ota:
  - platform: esphome
    password: !secret ota_password

  - platform: web_server

# Enable Home Assistant API (https://esphome.io/components/api, conflicts with mqtt:)
api:
  password: !secret api_password

# Get time from Home Assistant
#time:
#  - platform: homeassistant
#    id: ha_time

web_server:
  port: 80
  version: 3
  #auth:
    #username: !secret web_username
    #password: !secret web_password
